### ISSUE TITLE
New dewar or stick with the old?

### ISSUE THREAD

**Issue by dsand** [so-90prime/90prime#11]
Mike Lesser is looking into the possibility of using a dewar in his lab for the 'new' 90Prime.  This may minimize down time, if feasible.  It might also be expensive.

**Comment by dsand** [comment]
@mplesser is collecting quotes on a new dewar.  Any relevant info will be posted here.

**Comment by mplesser** [comment]
A new dewar with cart has been ordered from Universal Cryogenics.  We should have it in January.  No window is included.
