### ISSUE TITLE
Figure out computing needs for upgraded 90Prime

### ISSUE THREAD

**Issue by dsand** [so-90prime/90prime#14]
1. NUC to serve website.
2. New Azcam computer?
3. New Observer Computer?

[4] On mountain data reduction computer for Sand's group.  Hopefully more can be accomodated.

**Comment by pndaly** [comment]
1 - Yes, 2 - No, 3 - See #16

**Comment by dsand** [comment]
this issue may be defunct now with CJ's open issue.  I'm going to close it, but feel free to reopen if I got it wrong.
