### ISSUE TITLE
Computing upgrades to consider for 90 prime

### ISSUE THREAD

**Issue by cjastro** [so-90prime/90prime#16]
The new 90 prime will have new computing requirements and the old equipment should be refreshed.

1) we should upgrade the 90" to have a NUC "web presence" computer as we did at the 61 and VATT.  This computer is typically a windows computer that we use HyperV to install several linux VM's. One of those VM's is for web, and another is for other systems administration processes.  The systems we use at VATT and Kuiper have 8GB of ram.  Moving forward these should be 16GB.

2) We should upgrade teh observing computer, Bart.  Bart is currently ~6 year old hardware.  A refresh with modern hardware is needed

3) bokpop needs to go away.  Currently there is a logging system that resides on bokpop.  This system was designed to be a centralized location for acquiring telemetry.  This was a poor design decision.  Subsystems need to get their telemetry from their peers, and future logging systems should reside on our observing computer.

4) The new 90prime will be designed around a gigabit network interface, rather than the old fiber interface.  We need to redesign the network to the top ring, and choose an appropriate low power switch for the top ring.  The main switch for the 90 is currently about 12 years old.  It might be worth revisiting that, as well.

5) We need to revise the autoguider software.  We are using PHD2 pretty happily at the VATT.  This software would be able to live on the new observing computer.  A lot of this development depends heavily on what camera is chosen, whether we are still using legacy TCS, or if we have switched to TCS-NG.

**Comment by pndaly** [comment]
Can we get some idea of data capacity required? I'm told with 4x4 binning a 90Prime image is 32Mb. Assuming 300s exposures (and no overhead), that is a maximum of 384Mb/hour. Optimistically, assume a 10-hour night and round up a bit we
get 4Gb/night. How does that compare with current disk usage? If I also assume 250 nights/year, that's 1 Tb / year. Are these
figures reasonable?

**Comment by dsand** [comment]
Lets make that a bigger number.  CSS has ~30 sec exposures.  Our transient program will have something similar, or maybe we'll go a little longer so we're not overhead dominated.  Lets assume 5-10 Tb/year.  hard disks are cheap, lets be safe.

**Comment by pndaly** [comment]
Notwithstanding the above, many astronomers use MacBooks and bring them to the dome. Is there any reason we should not consider replacing the current observer computer with a MacMini and a big monitor or two? If the "observer computer" is generally used as a portal to other systems, I don't see any issue. However, if software runs on the observer computer, it would have to be Mac-compatible.

**Comment by davner** [comment]
1. Yes, sooner we get it the sooner I can finish a chunk of the 90prime development. The next step would be deciding who purchases it, from what account, and what model. 

2. I support exploring the idea of have a mac mini with a large desktop. There is some software running locally ie optoserver that would need to be capable to run on the mac. Sounds like something for Docker hehe. 

3. Yes, no more bokpop with the NUC possibly being logging and the webserver. The logging system would never be required for operations and I plan on only using that data for frontend monitors and logging websites.

5. It is safe to say we wont have the TCS-NG running by next summer. Could PHD2 run with legacy for now with the plan to switch to TCS-NG or is the overhead of doing that too much?

**Comment by dsand** [comment]
@davner: Let me get you an account number tonight.

**Comment by dsand** [comment]
After some brainstorming (April 19 2022), we decided we may need two computers and one NAS disk storage system.  One computer would run 90Prime, and the data would go to the NAS disk.  The second computer would run BANZAI and provide IQ data to the observer.  It should be a little beefier.  And it could serve as the backup to the 90Prime computer in a pinch.

Thoughts: Should make sure new 90Prime computer can run phd2 smoothly while operating telescope.

Will an NAS disk complicate things when dealing with Azcam and the windows machine?

**Comment by dsand** [comment]
One other requirement we should consider.  I want us to buy all of the necessary equipment so we do not have to shut the new computers down for 'lightning shutdown'.

**Comment by dsand** [comment]
Here is a [link](https://docs.google.com/spreadsheets/d/1oUyofoTTV-epGY0RK5o_s3X5FA0lqFqy/edit?usp=sharing&ouid=112166443502142977413&rtpof=true&sd=true) to @pndaly's computing plan in detail, with prices.

**Comment by dsand** [comment]
Much progress has been made here, and I have missed some details.  At this point some things like the NAS disk system have been ordered.  One issue that we are still investigating is where the new system will sit, physically.  Here is an email from @pndaly that captures the situation and our investigation path:

> At a meeting today between Dave, CJ, Chad and myself we discussed the (mainly) UPS options for the new rack and computers as part of
the 90Prime upgrade. Apologies in advance if this message sounds somewhat dictatorial but I'm trying to capture all the comments/requirements
whilst they are fresh in my mind.

>AFAIK, Summer will be at the Bok on Friday 6/3 (a week this Friday) and investigate further. Several things popped up during the meeting.

> 1. We will use fiber, only, to connect the network switch to the backbone. Within the rack, copper/rj45 is OK. The new switch supports fiber;
>2. The APC UPSs are fine and would be a purchase consistent with other mountain operations telescopes (tried and trusted technology);
>3. We will have 2 x Brickwall surge protectors which means we need to have 2 separate​ 20A circuits, 1 for each Brickwall;
>4. These circuits will be, preferably, dedicated to this upgrade equipment so we need to identify the circuits and any equipment currently attached.

>The best case scenario is that the office already has 2 separate 20A circuits with nothing attached and there is an easy fiber run to the nearest network
access point. Life rarely works out so optimistically, though, so we'd need to know about other options: 

> 1. Now if the office is not​ equipped with 2 separate 20A circuits, we need to know how difficult it is to either put 2 new, dedicated, circuits in or add a
single new one if the current one is deemed acceptable;
> 2. Another option is to split the racks into 2 separate (smaller) racks one for 'operations' and one for 'science'. These could then be hosted in separate
locations so each rack would require a dedicated 20A circuit and a fiber feed from the backbone. We'd have to buy a network switch for each rack.

>So, comments/thoughts are requested (using 'reply all' so that everyone is kept in the loop) on the above and the following tasks for Summer et al to achieve:

>Scenario 1: all equipment in 1 rack fed by 2 x 20A circuits and 1 fiber. Preferred location: office. We'd like Summer et al to take pics and
investigate this and report back on cable runs, power circuits currently installed, attached equipment etc. Pics of everything.

>Scenario 2: equipment is split between 2 racks where each​ rack requires 1 dedicated 20A circuit and 1 fiber feed. 1 rack would be in the office but
the other is TBD. As for scenario 1, we'd like pics and comments on the office and other viable locations;
