### ISSUE TITLE
New 90Prime shutter

### ISSUE THREAD

**Issue by dsand** [so-90prime/90prime#17]
There are funds in the budget to replace the original 90Prime shutter, which is still in use and has been worked on over the years.  

I believe this is the company: [Bonn shutter](https://www.bonn-shutter.de/)

Here is a 200mm shutter they sell: [200mm shutter](https://www.bonn-shutter.de/200x200.php)

Although it does not look like the shutter in the 90Prime SPIE (attached)
![Uploading Screen Shot 2020-08-31 at 12.35.43 PM.png…](90Prime shutter in SPIE paper)

Maybe we are using the 200mm shutter with the 'motors sitting on the top housing' mentioned here: [200mm shutter with top motors](https://www.bonn-shutter.de/customer_specific.php)

**Comment by dsand** [comment]
![Screen Shot 2020-08-31 at 12 35 43 PM](https://user-images.githubusercontent.com/9013064/91759683-e9dde580-eb86-11ea-89c7-efcc28dfb8f4.png)

This time with 90Prime shutter image from SPIE paper properly attached.

**Comment by mplesser** [comment]
I spoke with the Bonn shutter folks.  We need to understand if (mechanically) we can use the current style of 200 mm shutters which are "flat".  Specs and drawings are at https://www.bonn-shutter.de/200x200.php.

Can someone in Mountain Ops look at the instrument and determine if we can use a new "stock" Bonn shutter.  I think it is worth using a currently supported Bonn shutter of possible.

**Comment by dsand** [comment]
Mike -- can you recommend someone at Mtn Ops who can look at this?  Do we think it is Greg?

**Comment by mplesser** [comment]
Greg knows the shutter best.  The issue is probably mountain access and the physical mounting (bolt locations).  I do not know if that info is easily accessible.

I have asked Bonn for a cost estimate.  They also have a very slightly used (exhibition halls) 200 mm demo unit I am asking about to save money.

**Comment by dsand** [comment]
Update from @grstafford:

> At first glance, it looks like it will work. The links do not show how the shutter mounts, although I can mount it no matter what. I’ll need to go into my lab on campus and see if I have the Bonn Shutter manual we currently use and match the LxW with the new one.  Otherwise, I or someone like Joe, can check for me if he’s going up to the 90” before me. I’ll ping him as well. It is tight in the Top Box where the existing shutter is mounted, but this can be easily verified. The height should not be an issue at all as the motors are integrated into the shutter where they don’t protrude outside the shutter housing or increase the thickness (height) of the shutter.  The existing motors are mounted vertically and stick out of the main shutter package.  No big deal on these, just need verification so no surprises or mistakes.

**Comment by dsand** [comment]
Further update from @grstafford, and he is working with Joe to find a time to go to the telescope:

> The current Bonn Shutter on 90Prime is 672mm x 320mm x 85mm.
> 
> The new Bonn Shutter suggested will be 714mm x 300mm x 30mm
> 
>  
> 
> The width and height will be ok for sure.  Looks like the difference in length is 42mm. That’s 21mm on each end I will need to verify there is enough space to accommodate. I’ll need to go up to the 90” to verify there will be enough clearance.  There is a cable harness I need to check on that routes on the edge where that extra length may require me re-routing the harness.  No big deal if re-routing is necessary. And the new shutter has the connector on the end instead of on the side like the old shutter.  So, I’ll need to verify clearance.
> 
>  
> 
> I would like to have Joe with me when or if I can gain permission to travel to Kitt Peak.  I included Joe on this email.

**Comment by dsand** [comment]
We have ordered a new shutter.  The currently active shutter will serve as a back up.
