### ISSUE TITLE
Update to 90Prime Software Flowchart

### ISSUE THREAD

**Issue by dsand** [so-90prime/90prime#21]
After discussion, @danavner will flesh out the 90Prime flow chart, in collaboration with others in the group.  Here is v1:

https://github.com/so-90prime/90prime/blob/master/software-diagrams/overview-v1.pdf

**Comment by davner** [comment]
V2 is in final review passing Phil Daly's inspection and awaiting CJ's approval.

**Comment by dsand** [comment]
should we post v2 at https://github.com/so-90prime/90prime/blob/master/software-diagrams/ ?

**Comment by davner** [comment]
Yea it will appear there as overview-v2.pdf

**Comment by davner** [comment]
The diagram has been uploaded in commit: f018323

[Direct link here](https://github.com/so-90prime/90prime/blob/master/software-diagrams/overview-v2.pdf)
