### ISSUE TITLE
New Higher-Resolution Monitors for 90prime computer

### ISSUE THREAD

**Issue by dsand** [so-90prime/90prime#33]
At 11/22 meeting, it was suggested to buy new high-res monitors that will fit under the 90-in control room shelving.
The monitors Dave has are:
https://www.amazon.com/SAMSUNG-inch-UJ59-monitor-LU32J590UQNXZA/dp/B07CS3JGPC/ref=asc_df_B07CS3JGPC/?tag=hyprod-20&linkCode=df0&hvadid=312727440900&hvpos=&hvnetw=g&hvrand=10074390776554813975&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1013509&hvtargid=pla-578371569807&th=1

thumbs up, CJ?

**Comment by davner** [comment]
👍🏽 from me!
