### ISSUE TITLE
New shutter for 90Prime

### ISSUE THREAD

**Issue by dsand** [so-90prime/90prime#41]
The new shutter for 90Prime was received in late 2021.  This thread will document installation.

**Comment by dsand** [comment]
At 1/3/2021 meeting @grstafford indicated that this could be installed mid-January, and prior to the 90Prime engineering run (Jan 22).

**Comment by grstafford** [comment]
New 90Prime Bonn Shutter. Image attached
![New Bonn Shutter](https://user-images.githubusercontent.com/70164691/148436003-cb992bcb-5ce4-43c4-88c8-ef71db04ec49.jpg)

**Comment by dsand** [comment]
As of Jan 20, 2022 90Prime Software meeting the new 90Prime shutter has been operating for several days.

If nothing happens through the 90Prime engineering run, I will close this issue.

**Comment by dsand** [comment]
The shutter worked perfectly during the run.  Closing this issue!
