### ISSUE TITLE
Add environmental header keywords to 90Prime image

### ISSUE THREAD

**Issue by dsand** [so-90prime/90prime#63]
We would like basic weather information in the header of 90Prime images, including dome temperature, wind speed, relative humidity, etc

We understand that this is a bigger task that may require some Mtn Ops infrastructure, but it will be important info for observers.

**Comment by mplesser** [comment]
The azcam code already exists, it was disabled when bokpop went away.  If there is a source again I can reenable…

From: David Sand ***@***.***>
Sent: Wednesday, November 30, 2022 4:11 PM
To: so-90prime/90prime ***@***.***>
Cc: Lesser, Michael P - (mlesser) ***@***.***>; Assign ***@***.***>
Subject: [EXT]Re: [so-90prime/90prime] Add environmental header keywords to 90Prime image (Issue #63)


External Email

Assigned #63<https://github.com/so-90prime/90prime/issues/63> to @mplesser<https://github.com/mplesser>.

**Comment by pndaly** [comment]
Dunno what bokpop etc did but if you git pull the latest bokGalil code, there is now a file called src/Gaili_DMC_22x0_Read_Telemetry.py (which follows the regular naming convention) that can be imported to Python code or run from the command line:

  % python3 Galil_DMC_22x0_Read_Telemetry --help

will give you the options. As a command line example:

 % python3 Galil_DMC_22x0_Read_Telemetry --key=weather
{'dome': {'external_temperature': '45.74', 'external_humidity': '46.18', 'external_dewpoint': '31.4', 'internal_temperature': '48.07', 'internal_humidity': '42.40', 'internal_dewpoint': '32.0', 'control_room_temperature': '70.93', 'utc': '2022-12-01T06:10:59.629836+00:00', 'error': ''}, 'mirror_cell': {'temperature': '47.39', 'humidity': '55.38', 'dewpoint': '32.27', 'utc': '2022-12-01T06:10:59.645183+00:00', 'error': ''}, 'tube': {'utc': '2022-12-01T06:10:57.625438+00:00', 'error': ''}, 'upper_dome': {'temperature': '46.67', 'humidity': '50.16', 'dewpoint': '29.21', 'utc': '2022-12-01T06:10:59.980422+00:00', 'error': ''}, 'wind': {'speed': '8.44', 'direction': '145.50', 'gust_speed': '15.46', 'gust_direction': '97.34', 'utc': '2022-12-01T06:10:57.611134+00:00', 'error': ''}}

from the command line it returns a string but called from Python it returns a dictionary.

**Comment by mplesser** [comment]
I added Phil’s telemetry code to azcam as a test.  It works fine, but I have to write a parser to turn the dictionary into FITS keywords.  For now the code is enabled and prints to the server window, I think that is useful tonight to make sure it works well during observations.

You can disable this in the server window with “instrument.telemetry_enabled =0”.


From: Phil Daly ***@***.***>
Sent: Wednesday, November 30, 2022 11:12 PM
To: so-90prime/90prime ***@***.***>
Cc: Lesser, Michael P - (mlesser) ***@***.***>; Mention ***@***.***>
Subject: [EXT]Re: [so-90prime/90prime] Add environmental header keywords to 90Prime image (Issue #63)


External Email

Dunno what bokpop etc did but if you git pull the latest bokGalil code, there is now a file called src/Gaili_DMC_22x0_Read_Telemetry.py (which follows the regular naming convention) that can be imported to Python code or run from the command line:

% python3 Galil_DMC_22x0_Read_Telemetry --help

will give you the options. As a command line example:

% python3 Galil_DMC_22x0_Read_Telemetry --key=weather
{'dome': {'external_temperature': '45.74', 'external_humidity': '46.18', 'external_dewpoint': '31.4', 'internal_temperature': '48.07', 'internal_humidity': '42.40', 'internal_dewpoint': '32.0', 'control_room_temperature': '70.93', 'utc': '2022-12-01T06:10:59.629836+00:00', 'error': ''}, 'mirror_cell': {'temperature': '47.39', 'humidity': '55.38', 'dewpoint': '32.27', 'utc': '2022-12-01T06:10:59.645183+00:00', 'error': ''}, 'tube': {'utc': '2022-12-01T06:10:57.625438+00:00', 'error': ''}, 'upper_dome': {'temperature': '46.67', 'humidity': '50.16', 'dewpoint': '29.21', 'utc': '2022-12-01T06:10:59.980422+00:00', 'error': ''}, 'wind': {'speed': '8.44', 'direction': '145.50', 'gust_speed': '15.46', 'gust_direction': '97.34', 'utc': '2022-12-01T06:10:57.611134+00:00', 'error': ''}}

from the command line it returns a string but called from Python it returns a dictionary.

**Comment by dsand** [comment]
Thanks Mike, we will check it out.  Glad this was a relatively easy enhancement.

**Comment by mplesser** [comment]
The info is not in the header yet, I have to write that code.  But I can get it at the right time with Phil’s code…

From: David Sand ***@***.***>
Sent: Thursday, December 1, 2022 9:09 AM
To: so-90prime/90prime ***@***.***>
Cc: Lesser, Michael P - (mlesser) ***@***.***>; Mention ***@***.***>
Subject: [EXT]Re: [so-90prime/90prime] Add environmental header keywords to 90Prime image (Issue #63)


External Email

Thanks Mike, we will check it out. Glad this was a relatively easy enhancement.

**Comment by dsand** [comment]
I actually think we have environmental information in the header now.  I'll close this.
