### ISSUE TITLE
Replace damaged actuator

### ISSUE THREAD

**Issue by davner** [so-90prime/90prime#7]
## Description

The design of how the 3 actuators and their linkage mechanisms are used to focus has been a problem in the past. There have been several occasions where the actuator rods have bent because the linkages were able to flip into a bad position causing misalignment in the axial direction.

<img width="497" alt="Screen Shot 2020-08-13 at 11 54 43 PM" src="https://user-images.githubusercontent.com/46757810/90223654-4f7a5580-ddc3-11ea-9da4-3b68771739b8.png">

**Comment by dsand** [comment]
I believe Greg Safford replaced this some time in Spring 2021.  I'm closing this.
